// Code generated by licensepack; DO NOT EDIT.
package main

func init() {
	licenses = "## github.com/paulhammond/licensepack\n" +
		"\n" +
		"LICENSE.txt:\n" +
		"\n" +
		"Copyright © 2021 Paul Hammond\n" +
		"\n" +
		"Permission is hereby granted, free of charge, to any person obtaining a copy\n" +
		"of this software and associated documentation files (the \"Software\"), to deal\n" +
		"in the Software without restriction, including without limitation the rights\n" +
		"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n" +
		"copies of the Software, and to permit persons to whom the Software is\n" +
		"furnished to do so, subject to the following conditions:\n" +
		"\n" +
		"The above copyright notice and this permission notice shall be included in all\n" +
		"copies or substantial portions of the Software.\n" +
		"\n" +
		"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n" +
		"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n" +
		"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n" +
		"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n" +
		"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n" +
		"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n" +
		"SOFTWARE.\n" +
		"\n" +
		"## golang.org/pkg\n" +
		"\n" +
		"LICENSE:\n" +
		"\n" +
		"Copyright (c) 2009 The Go Authors. All rights reserved.\n" +
		"\n" +
		"Redistribution and use in source and binary forms, with or without\n" +
		"modification, are permitted provided that the following conditions are\n" +
		"met:\n" +
		"\n" +
		"   * Redistributions of source code must retain the above copyright\n" +
		"notice, this list of conditions and the following disclaimer.\n" +
		"   * Redistributions in binary form must reproduce the above\n" +
		"copyright notice, this list of conditions and the following disclaimer\n" +
		"in the documentation and/or other materials provided with the\n" +
		"distribution.\n" +
		"   * Neither the name of Google Inc. nor the names of its\n" +
		"contributors may be used to endorse or promote products derived from\n" +
		"this software without specific prior written permission.\n" +
		"\n" +
		"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n" +
		"\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n" +
		"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n" +
		"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n" +
		"OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n" +
		"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n" +
		"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n" +
		"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n" +
		"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n" +
		"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n" +
		"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n" +
		"\n" +
		"## golang.org/x/mod\n" +
		"\n" +
		"LICENSE:\n" +
		"\n" +
		"Copyright (c) 2009 The Go Authors. All rights reserved.\n" +
		"\n" +
		"Redistribution and use in source and binary forms, with or without\n" +
		"modification, are permitted provided that the following conditions are\n" +
		"met:\n" +
		"\n" +
		"   * Redistributions of source code must retain the above copyright\n" +
		"notice, this list of conditions and the following disclaimer.\n" +
		"   * Redistributions in binary form must reproduce the above\n" +
		"copyright notice, this list of conditions and the following disclaimer\n" +
		"in the documentation and/or other materials provided with the\n" +
		"distribution.\n" +
		"   * Neither the name of Google Inc. nor the names of its\n" +
		"contributors may be used to endorse or promote products derived from\n" +
		"this software without specific prior written permission.\n" +
		"\n" +
		"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n" +
		"\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n" +
		"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n" +
		"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n" +
		"OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n" +
		"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n" +
		"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n" +
		"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n" +
		"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n" +
		"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n" +
		"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n" +
		"\n" +
		"## golang.org/x/sys\n" +
		"\n" +
		"LICENSE:\n" +
		"\n" +
		"Copyright (c) 2009 The Go Authors. All rights reserved.\n" +
		"\n" +
		"Redistribution and use in source and binary forms, with or without\n" +
		"modification, are permitted provided that the following conditions are\n" +
		"met:\n" +
		"\n" +
		"   * Redistributions of source code must retain the above copyright\n" +
		"notice, this list of conditions and the following disclaimer.\n" +
		"   * Redistributions in binary form must reproduce the above\n" +
		"copyright notice, this list of conditions and the following disclaimer\n" +
		"in the documentation and/or other materials provided with the\n" +
		"distribution.\n" +
		"   * Neither the name of Google Inc. nor the names of its\n" +
		"contributors may be used to endorse or promote products derived from\n" +
		"this software without specific prior written permission.\n" +
		"\n" +
		"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n" +
		"\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n" +
		"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n" +
		"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n" +
		"OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n" +
		"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n" +
		"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n" +
		"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n" +
		"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n" +
		"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n" +
		"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n" +
		"\n" +
		"## golang.org/x/tools\n" +
		"\n" +
		"LICENSE:\n" +
		"\n" +
		"Copyright (c) 2009 The Go Authors. All rights reserved.\n" +
		"\n" +
		"Redistribution and use in source and binary forms, with or without\n" +
		"modification, are permitted provided that the following conditions are\n" +
		"met:\n" +
		"\n" +
		"   * Redistributions of source code must retain the above copyright\n" +
		"notice, this list of conditions and the following disclaimer.\n" +
		"   * Redistributions in binary form must reproduce the above\n" +
		"copyright notice, this list of conditions and the following disclaimer\n" +
		"in the documentation and/or other materials provided with the\n" +
		"distribution.\n" +
		"   * Neither the name of Google Inc. nor the names of its\n" +
		"contributors may be used to endorse or promote products derived from\n" +
		"this software without specific prior written permission.\n" +
		"\n" +
		"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n" +
		"\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n" +
		"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n" +
		"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n" +
		"OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n" +
		"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n" +
		"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n" +
		"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n" +
		"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n" +
		"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n" +
		"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n" +
		"\n"
}
