// Package license provides types for the data generated by licensepack.
package license

// Module represents a Go module. Some modules have more than one license file.
type Module struct {
	Name     string
	Licenses []File
}

// File represents a license file for a Go module.
type File struct {
	Path     string
	Contents string
}
